---
sudo: required
dist: trusty
language: node_js
node_js:
  - 11.0.0

branches:
  only:
    - master

cache:
  directories:
    - node_modules

services:
  - docker

env:
  global:
    - NODE_ENV=test
    - CODECOV_TOKEN="5e3112f7-a8bf-4652-bf65-585e3ec704c2"

install:
  - npm install -g codecov
  - npm install

before_script:
  - sudo service postgresql stop
  - docker ps
  - npm run infra
  - sleep 5
  - npm run db:migrate

script:
  - npm run test:coverage

after_success:
  - echo Upload code coverage 💪
  - codecov

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: "465bd3aa-0160-4f54-b100-1e65fc69bc48"
    app: dogbook-nodejsnights
    strategy: git
    on:
      branch:
        - master
      repo: bencheek/homework03
      
notifications:
  email: false